field: 4fbb28d9-5f55-47db-b772-301d46321c7c
fieldLayouts:
  d0a491eb-4ed2-4549-b5e0-c39f1733f950:
    tabs:
      -
        elements:
          -
            fieldUid: af60db8b-ccbf-4192-9a5c-fc0639d3899d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  af60db8b-ccbf-4192-9a5c-fc0639d3899d:
    contentColumnType: string
    fieldGroup: null
    handle: tickListItem
    instructions: ''
    name: 'Tick list item'
    searchable: true
    settings:
      columns:
        186:
          __assoc__:
            -
              - width
              - ''
      contentTable: '{{%stc_ticklistitem_3}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: ticklist
name: Ticklist
sortOrder: 1
