contentColumnType: text
fieldGroup: 57e17ebd-5a65-4486-a175-645b52fcf8e5
handle: cookieMessage
instructions: 'Appears in main bar on bottom'
name: 'Cookie message'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: 'This website uses cookies to ensure you get the best experience on our website. Declining cookies is fine'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
