contentColumnType: boolean
fieldGroup: f8f993ed-1301-42d7-92b2-acb531dbe101
handle: sticky
instructions: 'turn this on to make news item stay on the top heading space'
name: Sticky
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
