fieldLayouts:
  6b90017b-25b5-4ed5-ad0f-7f6925d06df4:
    tabs:
      -
        elements:
          -
            fieldUid: eb4dd8d4-526e-45bc-9df9-1798512dd7be
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88f481ab-083c-4016-a3a2-1ce22e2f1a55
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 854a81d0-40bc-45ae-ae97-3405888619f2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b94541a5-4fee-46e9-8f0d-59da799180c8
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c37dd07c-e401-4016-a7c9-bbfd7f66055a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0089a26-45cd-4af0-a9f2-5f78694a585c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Subscribe
        sortOrder: 1
handle: subscribe
name: Subscribe
